name: BentoTweaks
version: ${project.version}
main: me.shakeforprotein.bentotweaks.BentoTweaks
authors: [ShakeforProtein]
description: Custm game mechanics for Bentbox Skyblock and Acid Islands.
website: http://treebomc.com
api-version: 1.13